const swaggerAutogen = require('swagger-autogen')()

const outputFile = 'src/swagger_output.json'
const endpointsFiles = ['src/router.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "wishlist",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3333",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Client",
            "description": "client"
        },
        {
            "name": "Product",
            "description": "product"
        },
        {
            "name": "Wishlist",
            "description": "wishlist"
        },
        {
            "name": "Users",
            "description": "users"
        }
    ],
}


swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./dist/src/app')
});